version: "3.8"

services:
  app:
    build: .
    container_name: api42025
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npx ts-node src/server.ts
