name: Pipeline Funcionalidade

on:
  workflow_call:
    inputs:
      setup_run:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      SETUP_RUN: ${{ inputs.setup_run }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Run tests unit
        run: npm run test:unit

      - name: Run tests integration
        run: npm run test:integration
