name: CI Principal

on:
  pull_request:
    branches:
    - main
    - 'feat/*'
    - 'fix/*'
    - 'improve/*'
    - 'test/*'
    - 'refactor/*'

  jobs:
    check-branch:
      steps:
      - name: Get Branch Name
        run: echo "Branch name is ${{ github.head_ref }}"
    
    feature:
      if: startsWith(github.head_ref, 'feat/')
      uses: ./.github/workflows/feature.yml